### ISSUE TITLE
Can't use this library as dependency  in mmp project

### ISSUE THREAD

**Issue by Tolsi** [korlibs/kds#5]
I'm trying to make a simplified fork of your library :) and I want to inherit most of the common code and leave it mmp.

My [build.gradle  is here](https://github.com/Tolsi/aik/blob/master/geom/build.gradle).
```
dependencies {
    commonMainImplementation("com.soywiz:kds:1.5.0")
}
```

but when I compile it, then I have an import error in `com.soywiz.kds.*`. If I change it to `    commonMainImplementation("com.soywiz:kds-common:0.6.0")` I can see the dependency in the IntelliJ IDEA, but `gradle build` still has import errors like

```
e: /Users/tolsi/Documents/code/aik/geom/src/commonMain/kotlin/ru/tolsi/aik/geom/PointArrayList.kt: (23, 25): Unresolved reference: DoubleArrayList
...
```

What I do wrong? Can you help me build it?

**Comment by soywiz** [comment]
http://dl.bintray.com/korlibs/korlibs/com/soywiz/korlibs/kds/kds/1.9.2/

You have to include the repository: `http://dl.bintray.com/korlibs/korlibs/` or `jcenter()`

And the artifact should be:

`com.soywiz.korlibs.kds:kds:1.9.2`

I had to change the groupId to be able to publish it to jcenter.

**Comment by Tolsi** [comment]
Oh, it works! I spend 3 hours trying to fix it :< Can you update the readme for the future users?

**Comment by soywiz** [comment]
Yeah. Sorry, that was my fault. I have a pending issue of updating all my READMEs and the documentation website. Ill do that one ASAP

**Comment by soywiz** [comment]
I have just fixed all the references to the old bintray repo everywhere

**Comment by Tolsi** [comment]
It still failing.

```
repositories {
    maven { url "https://dl.bintray.com/korlibs/korlibs" }
}
dependencies {
    // For multiplatform projects
    implementation "com.soywiz:kds:1.9.2"
...
}
```

It should be at `https://dl.bintray.com/korlibs/korlibs/com/soywiz/kds/1.9.2/`, but correct is `https://dl.bintray.com/korlibs/korlibs/com/soywiz/korlibs/kds/kds/1.9.2/` - "com.soywiz.korlibs.kds:kds:1.9.2"

**Comment by soywiz** [comment]
You are right. It seems that I forgot to update the artifact . Thanks for pointing out.
